# -*- mode: ruby -*-

# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty64"

# Begin node1
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "hostname"

    node1.vm.provider "vmware_fusion" do |vf, override|
	override.vm.network "private_network", ip: "172.16.99.99"
        vf.vmx["numvcpus"] = "1"
        vf.vmx["memsize"] = "2048"
        vf.vmx["vhv.enable"] = "TRUE"
	vf.vmx["ethernet1.present"] = "TRUE"
    	vf.vmx["ethernet1.connectionType"] = "hostonly"
    	vf.vmx["ethernet1.virtualDev"] = "e1000"
    	vf.vmx["ethernet1.wakeOnPcktRcv"] = "FALSE"
    	vf.vmx["ethernet1.addressType"] = "generated"
	vf.vmx["ethernet1.vnet"]  = "vmnet1"
        vf.gui = "true"
      end

   node1.vm.provider "virtualbox" do |vb, override|
	override.vm.network "private_network", ip: "192.168.56.56"
        vb.customize [ "modifyvm", :id, "--cpus", "1" ]
        vb.customize [ "modifyvm", :id, "--memory", "1024" ]
	vb.customize [ "modifyvm", :id, "--hostonlyadapter2", "vboxnet0"]
    end
end
end
# End node1
